### ISSUE TITLE
Extract CCs of single omics

### ISSUE THREAD

**Issue by Arielode** [CostaLab/MOJITOO#3]
Hi, developers

Thanks for your brilliant tool for integrating multi-omics data!
I have noticed that Sup.Fig6 of your paper has shown the RNA-CC and ATAC-CC separately. I'd like to know how to extract this info in my Seurat object. There are MOJITOO reductions in the slot for each cell. 

Thanks!

**Comment by chengmingbo** [comment]
Hi Arielode,
Unfortunately, the current version does not include separate CCs for RNA and ATAC in the Seurat object. We will update a version to include this.

**Comment by chengmingbo** [comment]
We have added a parameter `keep_separated_reductions`  to keep the RNA_CC and ATAC_CC in the out object.

**Comment by storytc** [comment]
Hi Mingbo, 

Nice to hear that!! Thanks for your quick answer!
I see you have changed the code and limited the number of omics to 2. Is there any chance of dealing with tri-omics data? I have transcriptomes and two epigenome data....... >_<

Thanks!

**Comment by Arielode** [comment]
Hi Mingbo,

Nice to hear that!! Thanks for your quick answer!
I see you have changed the code and limited the number of omics to 2. Is there any chance of dealing with tri-omics data? I have transcriptomes and two epigenome data....... >_<

Thanks!

**Comment by chengmingbo** [comment]
Hi Arielode, 
MOJITOO can handle more than two modalities. However, it iteratively runs CCA to add modalities to unified CC components, meaning the separate CC components are merged in each iteration. If we were to retain the CC components for each iteration across more than two modalities, they would no longer be comparable. Therefore, the separate CC components for more than two modalities are not meaningful.

**Comment by Arielode** [comment]
Hi Mingbo,
Thank you for your great patience and huge help. I'll try a pairwise comparison. 
Have a nice day!
