### ISSUE TITLE
Extract significant CCs of specific omics

### ISSUE THREAD

**Issue by Arielode** [CostaLab/MOJITOO#4]
Hi, Mingbo

I'd like to ask that can i obtain the significant CCs of one omics rather than the whole CCs?
![image](https://github.com/user-attachments/assets/de1e04d2-ac73-4d43-be3a-c369e8cb60cb)

Thanks!

**Comment by chengmingbo** [comment]
Hi Arielode,
I don't understand what you mean. The correlation test tests the correlation between the CCs of the first and second omics.  It's impossible to test only a CC itself.

**Comment by Arielode** [comment]
Hi Mingbo,
I'm sorry that I didn't make myself clear. The MOJITOO reduction returns 4 factors. But when I access the omics-specific CCs, it returns a different number of CCs. I wonder if the variables "a" and "b" weren't filtered by significant test results in the unequal number of CCs.

**Comment by chengmingbo** [comment]
Hi Arielode,
The parameter `corr.pval` controls the number of MOJITOO factors based on correlation test. You can increase it to get more factors. On the other hand, the algorithm of Canonical Correlation Analysis(CCA) doesn't allow different numbers of CCs from different omics, meaning CCA can at most return CCs of min(#component_a, #component_b).

**Comment by Arielode** [comment]
Hi Mingbo, 
Thanks mingbo. I want to ask whether I can get the matrix of "a[, sig_idx]" and "b[, sig_idx]" rather than a and b with the parameter "keep_separated_reductions=T".

**Comment by chengmingbo** [comment]
Hi Arielode，
I would not implement this, keep all modality-specific component is useful for the checking the unrelated level. However, it's simple to get `a[, sig_idx]` and `b[, sig_idx]` by just checking `ncol(Embeddings(object[["MOJITOO"]]))`, which indicate the top `N` significant components.
